# Generated by Django 3.2.2 on 2021-08-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0003_alter_cake_category'),
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myadmin.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.usermaster')),
            ],
        ),
    ]
