# Generated by Django 3.2.2 on 2021-08-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_mycart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mycart',
            table='MyCart',
        ),
    ]
