# Generated by Django 3.2.2 on 2021-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_mycart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='carddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=4)),
                ('balance', models.FloatField(default=1000)),
            ],
            options={
                'db_table': 'CardDetails',
            },
        ),
    ]
