# Generated by Django 3.2.2 on 2021-08-10 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.CharField(default=datetime.datetime(2021, 8, 10, 13, 29, 1, 586025, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='imageurl',
            field=models.ImageField(default='abc.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.FloatField(default=199),
        ),
        migrations.AlterModelTable(
            name='cake',
            table='Cake',
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myadmin.categorie'),
        ),
    ]
